name: Deploy React App to Hostinger

# Run this workflow on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repo
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Use Node to build the app
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build your React app
      - name: Build
        run: npm run build

      # Step 5: Deploy via FTP to Hostinger
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build
          # The directory on your server where you'd like to upload the files
          server-dir: public_html
