name: Deploy React App to Hostinger

on:
  push:
    branches:
      - master  # Adjust if your branch name is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repository
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the React app
      - name: Build the React app
        run: |
          npm run build
          ls -al build/
          
      # 5. Deploy the build folder via FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          protocol: ftp
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 21
          local-dir: build/           # Ensure this points to the generated build folder
          server-dir: public_html/    # Ensure this matches the correct server directory
