name: Deploy React App to Hostinger

on:
  push:
    branches: [ "master" ]  # Change to "master" as per your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the React app
      - name: Build the React app
        run: npm run build

      # 5. Deploy the build folder via FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          protocol: ftp
          server: ${{ secrets.FTP_HOST }}
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build
          server-dir: public_html
          force-upload: true
